### ISSUE TITLE
pysptk issue

### ISSUE THREAD

**Issue by pcub** [r9y9/SPTK#14]
Hello, I am using sptk python in fedora.
however I get following error.

ImportError: /home/gg/.python-eggs/pysptk-0.1.4.dev0-py2.7-linux-x86_64.egg-tmp/pysptk/sptk.so: undefined symbol: b2c

I installed pysptk-0.1.5-dev recently, previously it was 0.1.4.
When I import pysptk, .python-eggs/pysptk-0.1.4.dev0-py2.7-linux-x86_64.egg-tmp generated automatically then python gives above error.

I want to use .python-eggs/pysptk-0.1.5.dev0-py2.7-linux-x86_64.egg-tmp as default.

I want to remove 0.1.4. But it automatically generated when python file runs.
How to solve this problem?
Thank you.

**Comment by r9y9** [comment]
Can you try to uninstall pysptk and re-install pysptk? Having different versions might be problematic. 

Also, please file a issue in https://github.com/r9y9/pysptk

**Comment by pcub** [comment]
I solved the issue. Problem was I used eclipse with python plugin, However when I use pycharm then pystpk worked as normal. 
THank you.

**Comment by r9y9** [comment]
Glad to head that. I will close this issue.
