### ISSUE TITLE
How can i generate the input  when i use  MLPG in SPTK 

### ISSUE THREAD

**Issue by xiaoyun4** [r9y9/SPTK#24]
when i try to use the toolkit MLPG in SPTK.  according to the  Instruction, the code: mlpg -m 24 -i 1 -d -0.5 0 0.5 -d 0.25 -0.5 0.25 sample.pdf > sample.mcep is right and  'sample.pdf' is the speech data used in EXAMPLE.  
When i try to generate the speech data by my own data, 
the length of vector is 1, therefore, -m is 0
the dynamic features can obtain by the relu: -0.5 0, 0.5 and 0.25 -0.5 0.25, the mean is itself, because the length of vector is 1each frame.  The covariance is variance of vectors of all frames. 
 when i try: mlpg -m 0 -i 0 -d -0.5 0 0.5 -d 0.25 -0.5 0.25 own.pdf > own.mcep, the output is bad. 

what's wrong? how can i obtain the mean and variance of static features and dynamic features?

Thanks

**Comment by r9y9** [comment]
Please ask to the SPTK official community: https://sourceforge.net/projects/sp-tk/

The code here is an unofficial fork and does not provide command line programs such as `mlpg`.
