### ISSUE TITLE
missing x2x, vopr and few others

### ISSUE THREAD

**Issue by cveaux** [r9y9/SPTK#25]
Hi, 
thanks for this project it looks very useful, however I was wondering if there's any special reason why you didn't make a wrapper for some SPTK functions such as x2x, vstat or vopr ?

Thanks

**Comment by r9y9** [comment]
Because we can just use numpy. e.g., `vopr -a` can be implemented by `x + x`.

**Comment by r9y9** [comment]
Oh, sorry, I thought the repo is https://github.com/r9y9/pysptk... but I don't think it's worth adding.

**Comment by cveaux** [comment]
Actually I intend to use it via the python wrapper pysptk and indeed I just realised after asking the question that all these functions can be implemented in a much easier way directly in python. Thanks for the reply.
